server:
  port: 8761
spring:
  application:
    name: factory-discovery-service
eureka:
  server:
    renewal-percent-threshold: 0.85
  client:
    register-with-eureka: false # 디스커버리에 자신을 등록할지 여부
    fetch-registry: false # 디스커버리에 있는 정보를 가져올지에 대한 여부
