server:
  port: 8761
spring:
  application:
    name: factory-discovery-service
eureka:
  client:
    register-with-eureka: false # ?? ???? Eureka ??? ???? ??
    fetch-registry: false # ?? ???? Eureka ???? ?? ??? ?????? ???? ??? ??
